version: '3.8'

services:
  akagera-booking-client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_APP_STAGING_API_URL: ${VITE_APP_STAGING_API_URL}
        VITE_APP_PRODUCTION_API_URL: ${VITE_APP_PRODUCTION_API_URL}
    environment:
      VITE_APP_STAGING_API_URL: ${VITE_APP_STAGING_API_URL}
      VITE_APP_PRODUCTION_API_URL: ${VITE_APP_PRODUCTION_API_URL}
      PORT: 3000
    ports:
      - 3000:3000
    env_file:
      - .env