import { UUID } from "crypto";
import { Activity } from "./activity.types";
import { BookingPerson } from "./bookingPerson.types";
import { BookingActivity } from "./bookingActivity.types";

export type Booking = {
    id: UUID;
    startDate: Date;
    notes?: Text;
    status: string;
    endDate: Date;
    phone?: string;
    email?: string;
    date: Date | string;
    totalAmountUsd?: number;
    totalAmountRwf?: number;
    discountedAmountUsd?: number;
    discountedAmountRwf?: number;
    checkIn?: Date | string;
    checkOut?: Date | string;
    createdAt: Date | string;
    updatedAt: Date | string;
    activities: Activity[];
    approvedBy?: UUID;
    approvedAt?: Date | string;
    approvedByUser?: string;
    referenceId?: string;
    entryGate?: string;
    exitGate?: string;
    name: string;
    type: string;
    bookingPeople?: BookingPerson[];
    bookingActivities?: BookingActivity[];
};
